 version: '3'
 services:
   tpcds_proxy:
     image: tpcds_benchmarking:2210
     volumes:
       - tpcds-mariadb_v2:/tpcds-mariadb
     container_name: tpcds_proxy
     entrypoint: /bin/bash
     tty: true
